title: "Travis CI 中文文档"
email: "support@travis-ci.com"
url: "https://docs.travis-ci.bestajax.com"
docs_github: "https://github.com/tuzhu008/docs-travis-ci-com_cn/"
exclude: [bin, CNAME, Gemfile, Gemfile.lock, README.md, slate, vendor, '*.erb']
markdown: kramdown
permalink: :/title/
syntax-highlighting:
  enabled: true
kramdown:
  hard_wrap: false
  input: GFM
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
sass:
  sass_dir: assets/stylesheets
